/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.UsuarioControlador;
import Modelo.Usuario;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.PreparedStatement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
/**
 *
 * @author maxi
 */
public class Login extends javax.swing.JFrame {
private Principal principal;
UsuarioControlador controladorLogin= new UsuarioControlador();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       
    }
 

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTuser = new javax.swing.JTextField();
        jPFpass = new javax.swing.JPasswordField();
        jbAceptar = new javax.swing.JButton();
        jbLimpiar1 = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Nakula", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Nakula", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña:");

        jTuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTuserKeyTyped(evt);
            }
        });

        jPFpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFpassKeyTyped(evt);
            }
        });

        jbAceptar.setBackground(new java.awt.Color(102, 102, 255));
        jbAceptar.setFont(new java.awt.Font("Nakula", 1, 18)); // NOI18N
        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });
        jbAceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jbAceptarKeyTyped(evt);
            }
        });

        jbLimpiar1.setBackground(new java.awt.Color(102, 102, 255));
        jbLimpiar1.setFont(new java.awt.Font("Nakula", 1, 18)); // NOI18N
        jbLimpiar1.setText("Limpiar");
        jbLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiar1ActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(102, 102, 255));
        jbSalir.setFont(new java.awt.Font("Nakula", 1, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTuser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPFpass, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbAceptar)
                        .addGap(34, 34, 34)
                        .addComponent(jbLimpiar1)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalir)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPFpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiar1)
                    .addComponent(jbSalir)
                    .addComponent(jbAceptar))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        // Boton aceptar
        
        validar();
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiar1ActionPerformed
        // Boton Limpiar
        limpiar();
    }//GEN-LAST:event_jbLimpiar1ActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // Boton salir
        this.dispose();
        principal.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jTuserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTuserKeyTyped
        char tecla = evt.getKeyChar();
        if(tecla == (char) evt.VK_ENTER){
            validar();
        }
    }//GEN-LAST:event_jTuserKeyTyped

    private void jbAceptarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAceptarKeyTyped
         char tecla = evt.getKeyChar();
        if(tecla == (char) evt.VK_ENTER){
            validar();
    }//GEN-LAST:event_jbAceptarKeyTyped
   }
    private void jPFpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFpassKeyTyped
         char tecla = evt.getKeyChar();
        if(tecla == (char) evt.VK_ENTER){
            validar();
    }//GEN-LAST:event_jPFpassKeyTyped
    }
    
    private void validar(){
         principal.setEnabled(false);
         if(jTuser.getText().length() > 0 && jPFpass.getPassword().length >0) {
             SwingWorker sw;
             sw = new SwingWorker(){
              @Override
              protected Object doInBackground() throws Exception {
                  Usuario usuario = new Usuario();
                  Usuario usuarioAux= null;
                  usuario.setUser(jTuser.getText());
                  char[] clave= jPFpass.getPassword();
                  String pass= new String (clave);
                  usuario.setPass(pass);
                  usuarioAux = controladorLogin.validar(usuario);
                  if(usuarioAux != null){
                      Principal.usuario = usuarioAux;
                      principal.setEnabled(true);
                      dispose();
                   
                  }else {
                      principal.setEnabled(true);
                      JOptionPane.showMessageDialog(null, "Verifique usuario/contraseña", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                      limpiar();
                  }
                  return null;
                }
                  
              };
             sw.execute();
                 
             }else {
                JOptionPane.showMessageDialog(this, "Falta ingresar usuario/contraseña", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                  }
             }
         private void limpiar(){
             jTuser.setText("");
             jPFpass.setText("");
         }
         
         private class Validar extends SwingWorker<Boolean, JInternalFrame>{

        public Validar() {
        }

        @Override
        protected void done() {
            super.done(); 
            principal.setEnabled(true);
            dispose();
        }

        @Override
        protected Boolean doInBackground() throws Exception {
            
            Usuario usuario = new Usuario();
            Usuario usuarioAux = null;
            usuario.setUser(jTuser.getText());
            char[] clave= jPFpass.getPassword();
                  String pass= new String (clave);
                  usuario.setPass(pass);
                  usuarioAux = controladorLogin.validar(usuario);
                  if(usuarioAux != null){
                      Principal.usuario = usuarioAux;
                     return true;
                   
                  }else {        
                      limpiar();
                      return false;
                  }
                 
              }
             
            }
         
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPFpass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTuser;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbLimpiar1;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
}
